[package]
authors = ["Samlet <xiaofei.wu@gmail.com>"]
name = "cc-sandbox"
version = "0.1.0"
edition = "2018"

[dependencies]
rayon = "1.0.2"
pyo3 = { version="0.13", features = ["extension-module"] }

[lib]
name = "cc_sandbox"
crate-type = ["cdylib"]
